package org.hexaphone.bootscreen;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

/**
 * One entry from manifest.json in jgm240/hexaphone-apps' bootscreen/
 * directory -- generated by vendor/hexaphone/art/gen_bootscreen_presets.py,
 * which is also the source of truth for the sha256/sizeBytes pins here.
 */
final class BootscreenPreset {
    static final String BASE_URL =
            "https://raw.githubusercontent.com/jgm240/hexaphone-apps/main/bootscreen/";

    final String id;
    final String displayName;
    final String file;
    final String sha256;
    final long sizeBytes;

    private BootscreenPreset(String id, String displayName, String file, String sha256,
            long sizeBytes) {
        this.id = id;
        this.displayName = displayName;
        this.file = file;
        this.sha256 = sha256;
        this.sizeBytes = sizeBytes;
    }

    String downloadUrl() {
        return BASE_URL + file;
    }

    static List<BootscreenPreset> parseManifest(String json) throws JSONException {
        List<BootscreenPreset> presets = new ArrayList<BootscreenPreset>();
        JSONObject root = new JSONObject(json);
        JSONArray array = root.getJSONArray("presets");
        for (int i = 0; i < array.length(); i++) {
            JSONObject entry = array.getJSONObject(i);
            presets.add(new BootscreenPreset(
                    entry.getString("id"),
                    entry.getString("displayName"),
                    entry.getString("file"),
                    entry.getString("sha256"),
                    entry.getLong("sizeBytes")));
        }
        return presets;
    }
}
