package org.hexaphone.bootscreen;

import android.app.Activity;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Lists the boot animation presets published in jgm240/hexaphone-apps
 * (bootscreen/manifest.json, generated by
 * vendor/hexaphone/art/gen_bootscreen_presets.py) and lets the user pick
 * one. "Customizable" here means picking from a curated color x speed
 * matrix, not live parametric rendering -- the stock bootanimation format
 * is just pre-rendered PNG frames, there's no color/speed knob to read at
 * boot time.
 */
public class MainActivity extends Activity implements ApplyPresetTask.Listener {

    // Tracks which preset was last successfully applied -- purely local
    // UI state (there's no system property to read back any more; see
    // ApplyPresetTask's class comment for why writing the fixed
    // bootanimation.zip filename directly is enough on its own).
    private static final String PREFS_NAME = "bootscreen";
    private static final String KEY_CURRENT_PRESET_ID = "current_preset_id";

    private LinearLayout listContainer;
    private TextView emptyState;
    private final Map<String, RowViews> rowsById = new HashMap<String, RowViews>();
    private ApplyPresetTask runningTask;

    private static class RowViews {
        BootscreenPreset preset;
        TextView status;
        Button action;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        listContainer = (LinearLayout) findViewById(R.id.list_container);
        emptyState = (TextView) findViewById(R.id.empty_state);

        loadManifest();
    }

    private void loadManifest() {
        emptyState.setText(R.string.loading);
        emptyState.setVisibility(View.VISIBLE);
        new ManifestFetchTask(new ManifestFetchTask.Listener() {
            @Override
            public void onManifestResult(ManifestFetchTask.Result result) {
                if (result.error != null) {
                    emptyState.setText(getString(R.string.manifest_error, result.error));
                    emptyState.setVisibility(View.VISIBLE);
                    return;
                }
                showPresets(result.presets);
            }
        }).execute();
    }

    private void showPresets(List<BootscreenPreset> presets) {
        emptyState.setVisibility(View.GONE);
        listContainer.removeAllViews();
        rowsById.clear();

        String currentId = getSharedPreferences(PREFS_NAME, MODE_PRIVATE)
                .getString(KEY_CURRENT_PRESET_ID, null);
        LayoutInflater inflater = LayoutInflater.from(this);

        for (BootscreenPreset preset : presets) {
            View row = inflater.inflate(R.layout.row_preset, listContainer, false);
            TextView name = (TextView) row.findViewById(R.id.row_name);
            final TextView status = (TextView) row.findViewById(R.id.row_status);
            final Button action = (Button) row.findViewById(R.id.row_action);

            name.setText(preset.displayName);

            final RowViews rv = new RowViews();
            rv.preset = preset;
            rv.status = status;
            rv.action = action;
            rowsById.put(preset.id, rv);

            setRowApplied(rv, preset.id.equals(currentId));

            action.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    applyPreset(rv);
                }
            });

            listContainer.addView(row);
        }
    }

    private void applyPreset(final RowViews rv) {
        if (runningTask != null) {
            return;
        }
        for (RowViews other : rowsById.values()) {
            other.action.setEnabled(false);
        }
        runningTask = new ApplyPresetTask(rv.preset, this);
        currentTaskRow = rv;
        runningTask.execute();
    }

    // Set right before execute() -- ApplyPresetTask.Listener callbacks
    // need to know which row they're updating, and there's only ever one
    // task running at a time (see the guard in applyPreset()).
    private RowViews currentTaskRow;

    @Override
    public void onStatus(final String status) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                if (currentTaskRow != null) {
                    currentTaskRow.status.setVisibility(View.VISIBLE);
                    currentTaskRow.status.setText(status);
                }
            }
        });
    }

    @Override
    public void onError(final String error) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                if (currentTaskRow != null) {
                    currentTaskRow.status.setVisibility(View.VISIBLE);
                    currentTaskRow.status.setText(error);
                }
                finishTask();
            }
        });
    }

    @Override
    public void onApplied() {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                if (currentTaskRow != null) {
                    getSharedPreferences(PREFS_NAME, MODE_PRIVATE).edit()
                            .putString(KEY_CURRENT_PRESET_ID, currentTaskRow.preset.id)
                            .apply();
                }
                for (RowViews rv : rowsById.values()) {
                    setRowApplied(rv, rv == currentTaskRow);
                }
                finishTask();
            }
        });
    }

    private void finishTask() {
        runningTask = null;
        currentTaskRow = null;
        for (RowViews rv : rowsById.values()) {
            rv.action.setEnabled(true);
        }
    }

    private void setRowApplied(RowViews rv, boolean applied) {
        if (applied) {
            rv.status.setVisibility(View.VISIBLE);
            rv.status.setText(R.string.status_applied);
            rv.action.setText(R.string.action_reapply);
        } else {
            rv.status.setVisibility(View.GONE);
            rv.action.setText(R.string.action_apply);
        }
    }
}
